# Generated by Django 5.0.3 on 2024-04-09 18:46

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0003_estudante_data_nascimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudante',
            name='data_nascimento',
            field=models.DateField(auto_created=builtins.input),
        ),
    ]
