# Generated by Django 5.0.3 on 2024-04-11 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0004_alter_estudante_data_nascimento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='descricao',
        ),
    ]
