# Generated by Django 5.0.3 on 2024-04-11 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0005_remove_categoria_descricao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudante',
            name='data_nascimento',
        ),
    ]
